modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]]

modId="better_animation_mob"
version="${file.jarVersion}"
displayName="Expasion"
logoFile="Expasionmod.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"

description='''
'''
[[dependencies.better_animation_mob]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_animation_mob]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
